# Generated by Django 4.2.6 on 2023-10-10 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images/course/')),
                ('intro', models.FileField(upload_to='video/course/')),
                ('spot_player_license', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('teacher', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('season', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_course', to='course.coursecategorymodel')),
            ],
        ),
    ]
