# Generated by Django 4.2.7 on 2023-11-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_subcategorymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCategoryModel',
            new_name='CourseSubCategoryModel',
        ),
    ]
