# Generated by Django 4.2.7 on 2023-11-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_coursemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='intro',
        ),
    ]
