# Generated by Django 4.2.7 on 2023-11-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_blogmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.DeleteModel(
            name='FeedbackModel',
        ),
    ]
