# Generated by Django 4.2.7 on 2023-11-11 08:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_ordersmodel_orderitemmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdersModel',
            new_name='OrderModel',
        ),
    ]
