# Generated by Django 4.2.7 on 2023-12-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_rename_ordersmodel_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategorymodel',
            name='class_des',
            field=models.CharField(default='course_category', max_length=20),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='class_des',
            field=models.CharField(default='course', max_length=20),
        ),
        migrations.AddField(
            model_name='coursesubcategorymodel',
            name='class_des',
            field=models.CharField(default='course_subcategory', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='class_des',
            field=models.CharField(default='order_item', max_length=20),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='class_des',
            field=models.CharField(default='order', max_length=20),
        ),
        migrations.AddField(
            model_name='sampleexercisemodel',
            name='class_des',
            field=models.CharField(default='sample_exercise', max_length=20),
        ),
    ]
