# Generated by Django 4.2.7 on 2024-02-05 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_coursecategorymodel_class_des_coursemodel_class_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
