# Generated by Django 4.2.7 on 2024-02-10 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_coursemodel_created_coursemodel_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_order', to='course.coursemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
