# Generated by Django 4.2.7 on 2024-02-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_ordermodel_course_alter_coursemodel_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_course', to='course.coursecategorymodel'),
        ),
    ]
