# Generated by Django 4.2.7 on 2024-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_coursemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategorymodel',
            name='hovered_icon',
            field=models.ImageField(default=1, upload_to='images/icon/category/'),
            preserve_default=False,
        ),
    ]
