# Generated by Django 4.2.7 on 2024-02-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_coursecategorymodel_hovered_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategorymodel',
            name='hovered_icon',
            field=models.FileField(upload_to='images/icon/category/'),
        ),
        migrations.AlterField(
            model_name='coursecategorymodel',
            name='icon',
            field=models.FileField(upload_to='images/icon/category/'),
        ),
    ]
