# Generated by Django 4.2.7 on 2024-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_coursecategorymodel_hovered_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategorymodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='coursesubcategorymodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='coursesubcategorymodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='sampleexercisemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sampleexercisemodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='sampleexercisemodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='sampleexercisemodel',
            name='sample_exercise',
        ),
        migrations.RemoveField(
            model_name='sampleexercisemodel',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='sampleexercisemodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='coursesubcategorymodel',
            name='subcategory',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
