# Generated by Django 4.2.7 on 2024-02-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_coursecategorymodel_hovered_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecategorymodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='coursemodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='coursesubcategorymodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='class_des',
        ),
        migrations.RemoveField(
            model_name='sampleexercisemodel',
            name='class_des',
        ),
    ]
