# Generated by Django 4.2.7 on 2024-02-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_remove_coursecategorymodel_class_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='percent_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
