# Generated by Django 4.2.7 on 2024-03-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_coursemodel_percent_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='contacts_course',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='target_course',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
