# Generated by Django 4.2.7 on 2024-02-21 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0019_coursesubcategorymodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleexercisemodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_sample', to='course.coursecategorymodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleexercisemodel',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_sample', to='course.coursemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleexercisemodel',
            name='sample_exercise',
            field=models.FileField(default=1, upload_to='video/sample/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleexercisemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_sample', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
