# Generated by Django 4.2.7 on 2024-02-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_sampleexercisemodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleexercisemodel',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_sample', to='course.coursesubcategorymodel'),
            preserve_default=False,
        ),
    ]
