# Generated by Django 5.0.3 on 2024-04-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_coursemodel_contacts_course_coursemodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='intro',
            field=models.FileField(default=1, upload_to='video/course/intro/'),
            preserve_default=False,
        ),
    ]
