# Generated by Django 5.0.3 on 2024-04-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_coursemodel_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='intro',
        ),
    ]
