# Generated by Django 5.0.3 on 2024-04-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_remove_coursemodel_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='intro',
            field=models.FileField(blank=True, null=True, upload_to='video/course/intro/'),
        ),
    ]
