# Generated by Django 5.0.3 on 2024-04-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_coursemodel_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='subtitle',
            field=models.BooleanField(default=False),
        ),
    ]
