# Generated by Django 5.0.3 on 2024-04-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_remove_coursemodel_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleexercisemodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sampleexercisemodel',
            name='subcategory',
        ),
    ]
