# Generated by Django 5.0.3 on 2024-04-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deaf',
            field=models.BooleanField(default=False),
        ),
    ]
