# Generated by Django 4.2.7 on 2024-02-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursemodel',
            name='price',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercoursemodel',
            name='ref_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
