# Generated by Django 4.2.7 on 2024-02-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_usercoursemodel_price_usercoursemodel_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursemodel',
            name='ref_id',
        ),
    ]
