# Generated by Django 4.2.7 on 2023-11-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
