# Generated by Django 4.2.7 on 2023-12-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogmodel_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='class_des',
            field=models.CharField(default='blog', max_length=20),
        ),
    ]
