# Generated by Django 4.2.7 on 2024-03-03 13:48

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='class_des',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='banner',
            field=models.ImageField(default=1, upload_to='images/blog/banner/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(upload_to='images/blog/images/'),
        ),
    ]
