# Generated by Django 5.0.3 on 2024-04-02 13:24

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogmodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
