# Generated by Django 5.0.3 on 2024-04-03 13:58

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='icon',
            field=models.ImageField(default=1, upload_to='images/blog/images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
