# Generated by Django 5.0.3 on 2024-04-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogmodel_icon_alter_blogmodel_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='image',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=models.TextField(),
        ),
    ]
