# Generated by Django 5.0.3 on 2024-04-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogmodel_image_alter_blogmodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
