# Generated by Django 5.0.3 on 2024-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogmodel_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='abstract',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
