# Generated by Django 4.2.7 on 2023-12-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='class_des',
            field=models.CharField(default='feedback', max_length=20),
        ),
        migrations.AddField(
            model_name='headerimagemodel',
            name='class_des',
            field=models.CharField(default='image_header', max_length=20),
        ),
    ]
