# Generated by Django 4.2.7 on 2024-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_feedbackmodel_class_des_headerimagemodel_class_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='images/header')),
                ('header_logo', models.FileField(upload_to='images/home_setting/')),
                ('footer_logo', models.FileField(upload_to='images/home_setting/')),
                ('class_des', models.CharField(default='image_header', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='HeaderImageModel',
        ),
    ]
