# Generated by Django 4.2.7 on 2024-02-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homesettingmodel_delete_headerimagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homesettingmodel',
            old_name='image',
            new_name='banner',
        ),
    ]
