# Generated by Django 5.0.3 on 2024-03-28 13:11

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_image_homesettingmodel_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', django_ckeditor_5.fields.CKEditor5Field()),
                ('spot', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
    ]
