# Generated by Django 5.0.3 on 2024-03-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_guidemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidemodel',
            old_name='spot',
            new_name='spot_player',
        ),
    ]
