# Generated by Django 4.2.7 on 2024-02-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemmodel',
            old_name='product',
            new_name='course',
        ),
    ]
