# Generated by Django 4.2.7 on 2024-02-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_product_orderitemmodel_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='authority',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
