# Generated by Django 5.0.3 on 2024-04-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_ordermodel_ref_id_ordermodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.CharField(max_length=100)),
                ('referral_code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.CharField(blank=True, max_length=20, null=True)),
                ('discount_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
