# Generated by Django 5.0.3 on 2024-04-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_discountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='deaf',
            field=models.BooleanField(default=False),
        ),
    ]
